// content/recorder.js — Event listener injector and capture engine

(() => {
  // Guard against double injection
  if (window.__automaton_scribe_injected__) return;
  window.__automaton_scribe_injected__ = true;

  let recording = false;
  let verifyMode = false;
  const listeners = [];

  // --- Deduplication ---
  let lastEvent = null;
  const DEDUP_WINDOW_MS = 50;

  function isDuplicate(type, target) {
    if (!lastEvent) return false;
    const now = Date.now();
    return lastEvent.type === type &&
           lastEvent.target === target &&
           (now - lastEvent.time) < DEDUP_WINDOW_MS;
  }

  function trackEvent(type, target) {
    lastEvent = { type, target, time: Date.now() };
  }

  // --- Element label resolution ---
  function getElementLabel(el) {
    if (!el) return 'unknown';
    const ariaLabel = el.getAttribute('aria-label');
    if (ariaLabel) return ariaLabel;
    const placeholder = el.getAttribute('placeholder');
    if (placeholder) return placeholder;
    const text = (el.innerText || '').trim();
    if (text && text.length <= 30) return text;
    if (text) return text.substring(0, 30) + '...';
    const title = el.getAttribute('title');
    if (title) return title;
    const tag = el.tagName.toLowerCase();
    const type = el.getAttribute('type');
    return type ? `${tag}[type=${type}]` : tag;
  }

  // --- Send event to panel ---
  function sendEvent(payload) {
    chrome.runtime.sendMessage({
      type: 'EVENT_CAPTURED',
      target: 'panel',
      payload,
    });
  }

  // --- Capture: Clicks ---
  function onClickCapture(e) {
    if (!recording) return;

    if (verifyMode) {
      e.preventDefault();
      e.stopPropagation();
      e.stopImmediatePropagation();

      const el = e.target;
      const selectorResult = getBestSelector(el);
      const textContent = (el.innerText || '').trim().substring(0, 100);
      const value = el.value || null;

      // Visual confirmation flash
      if (typeof flashConfirm === 'function') flashConfirm(el);

      sendEvent({
        type: 'verify',
        selector: selectorResult.selector,
        confidence: selectorResult.confidence,
        shadowDom: selectorResult.shadowDom,
        textContent,
        value,
        label: getElementLabel(el),
        timestamp: Date.now(),
      });
      return;
    }

    const el = e.target;
    if (isDuplicate('click', el)) return;
    trackEvent('click', el);

    const selectorResult = getBestSelector(el);
    sendEvent({
      type: 'click',
      selector: selectorResult.selector,
      confidence: selectorResult.confidence,
      shadowDom: selectorResult.shadowDom,
      label: getElementLabel(el),
      timestamp: Date.now(),
    });
  }

  // --- Capture: Input (change events, debounced) ---
  const inputTimers = new WeakMap();

  function onInputChange(e) {
    if (!recording || verifyMode) return;
    const el = e.target;
    if (!['INPUT', 'TEXTAREA', 'SELECT'].includes(el.tagName)) return;

    // Clear existing debounce timer for this element
    const existing = inputTimers.get(el);
    if (existing) clearTimeout(existing);

    inputTimers.set(el, setTimeout(() => {
      inputTimers.delete(el);

      const selectorResult = getBestSelector(el);
      const isPassword = el.type === 'password';
      sendEvent({
        type: 'input',
        selector: selectorResult.selector,
        confidence: selectorResult.confidence,
        shadowDom: selectorResult.shadowDom,
        value: isPassword ? '••••••••' : el.value,
        label: getElementLabel(el),
        timestamp: Date.now(),
      });
    }, 300));
  }

  // --- Capture: Scroll ---
  let scrollTimer = null;

  function onScroll() {
    if (!recording || verifyMode) return;

    if (scrollTimer) clearTimeout(scrollTimer);
    scrollTimer = setTimeout(() => {
      scrollTimer = null;
      sendEvent({
        type: 'scroll',
        scrollX: Math.round(window.scrollX),
        scrollY: Math.round(window.scrollY),
        // Best-effort: find nearest landmark element at viewport center
        landmarkLabel: findNearestLandmark(),
        timestamp: Date.now(),
      });
    }, 500);
  }

  function findNearestLandmark() {
    const centerX = window.innerWidth / 2;
    const centerY = window.innerHeight / 2;
    const el = document.elementFromPoint(centerX, centerY);
    if (!el) return null;

    // Walk up to find a meaningful element
    let current = el;
    for (let i = 0; i < 5 && current; i++) {
      if (current.id && !isAutoGeneratedId(current.id)) return `#${current.id}`;
      const ariaLabel = current.getAttribute('aria-label');
      if (ariaLabel) return ariaLabel;
      const role = current.getAttribute('role');
      if (role && ['main', 'navigation', 'banner', 'contentinfo', 'region'].includes(role)) {
        return `[role="${role}"]`;
      }
      current = current.parentElement;
    }
    return null;
  }

  // --- Capture: Key presses (Enter, Tab, Escape) ---
  const CAPTURED_KEYS = ['Enter', 'Tab', 'Escape'];

  function onKeyDown(e) {
    if (!recording || verifyMode) return;
    if (!CAPTURED_KEYS.includes(e.key)) return;
    if (isDuplicate('keypress', e.target)) return;
    trackEvent('keypress', e.target);

    const selectorResult = getBestSelector(e.target);
    sendEvent({
      type: 'keypress',
      key: e.key,
      selector: selectorResult.selector,
      confidence: selectorResult.confidence,
      shadowDom: selectorResult.shadowDom,
      label: getElementLabel(e.target),
      timestamp: Date.now(),
    });
  }

  // --- Verify mode: hover highlight ---
  function onMouseMoveVerify(e) {
    if (!recording || !verifyMode) return;
    if (typeof showHighlight === 'function') showHighlight(e.target);
  }

  // --- Listener management ---
  function addListener(target, event, handler, options) {
    target.addEventListener(event, handler, options);
    listeners.push({ target, event, handler, options });
  }

  function startRecording() {
    recording = true;
    verifyMode = false;

    addListener(document, 'click', onClickCapture, { capture: true });
    addListener(document, 'input', onInputChange, { capture: true });
    addListener(document, 'change', onInputChange, { capture: true });
    addListener(window, 'scroll', onScroll, { passive: true });
    addListener(document, 'keydown', onKeyDown, { capture: true });
    addListener(document, 'mousemove', onMouseMoveVerify, { passive: true });
  }

  function stopRecording() {
    recording = false;
    verifyMode = false;

    for (const { target, event, handler, options } of listeners) {
      target.removeEventListener(event, handler, options);
    }
    listeners.length = 0;

    // Clean up highlighter
    if (typeof removeOverlay === 'function') removeOverlay();

    // Allow re-injection
    window.__automaton_scribe_injected__ = false;
  }

  // --- Message handler ---
  chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    switch (message.type) {
      case 'START_RECORDING':
        startRecording();
        sendResponse({ ok: true });
        break;
      case 'STOP_RECORDING':
        stopRecording();
        sendResponse({ ok: true });
        break;
      case 'ENABLE_VERIFY_MODE':
        verifyMode = true;
        if (typeof ensureOverlay === 'function') ensureOverlay();
        sendResponse({ ok: true });
        break;
      case 'DISABLE_VERIFY_MODE':
        verifyMode = false;
        if (typeof hideHighlight === 'function') hideHighlight();
        sendResponse({ ok: true });
        break;
    }
  });

  // Auto-start if injected while recording should be active
  startRecording();
})();
