// content/selector.js — Modular selector engine

/**
 * Check if a selector uniquely identifies the element in the document.
 */
function isUnique(selector, element) {
  try {
    const root = element.getRootNode();
    return root.querySelector(selector) === element;
  } catch {
    return false;
  }
}

/**
 * Heuristic: is this ID likely auto-generated?
 */
function isAutoGeneratedId(id) {
  if (!id) return true;
  // Contains sequences of 5+ digits, or matches framework patterns
  if (/\d{5,}/.test(id)) return true;
  if (/^(ember|react|ng-|css-|:r\d|radix-|headlessui-)/.test(id)) return true;
  if (/^[a-f0-9]{8,}$/.test(id)) return true; // hex hash
  return false;
}

/**
 * Heuristic: is this class name meaningful (not a utility/framework token)?
 */
function isMeaningfulClass(cls) {
  if (cls.length <= 1) return false;
  if (/^\d+$/.test(cls)) return false;
  // Filter framework utility classes
  if (/^(ng-|css-|_|svelte-|tw-|sc-|chakra-|MuiTypography|MuiButton|jsx-)/.test(cls)) return false;
  // Tailwind-like single-purpose classes (e.g., "p-4", "mt-2", "text-sm", "bg-red-500")
  if (/^[a-z]{1,3}-[\da-z]/.test(cls) && cls.length < 12) return false;
  return true;
}

// --- Selector strategies (ordered by priority) ---

const strategies = [
  // Strategy 1: ID
  {
    name: 'id',
    confidence: 'high',
    run(element) {
      const id = element.id;
      if (!id || isAutoGeneratedId(id)) return null;
      const selector = `#${CSS.escape(id)}`;
      return isUnique(selector, element) ? selector : null;
    },
  },

  // Strategy 2: Data / ARIA attributes (Playwright-style)
  {
    name: 'data-attr',
    confidence: 'high',
    run(element) {
      const attrs = ['data-testid', 'data-test', 'data-cy', 'data-qa'];
      for (const attr of attrs) {
        const val = element.getAttribute(attr);
        if (val) {
          const selector = `[${attr}="${CSS.escape(val)}"]`;
          if (isUnique(selector, element)) return selector;
        }
      }
      // aria-label
      const ariaLabel = element.getAttribute('aria-label');
      if (ariaLabel) {
        const selector = `[aria-label="${CSS.escape(ariaLabel)}"]`;
        if (isUnique(selector, element)) return selector;
      }
      // name attribute
      const name = element.getAttribute('name');
      if (name) {
        const tag = element.tagName.toLowerCase();
        const selector = `${tag}[name="${CSS.escape(name)}"]`;
        if (isUnique(selector, element)) return selector;
      }
      // role + accessible name combo
      const role = element.getAttribute('role');
      if (role && ariaLabel) {
        const selector = `[role="${role}"][aria-label="${CSS.escape(ariaLabel)}"]`;
        if (isUnique(selector, element)) return selector;
      }
      return null;
    },
  },

  // Strategy 3: Class-based selector
  {
    name: 'class',
    confidence: 'medium',
    run(element) {
      const tag = element.tagName.toLowerCase();
      const classes = Array.from(element.classList).filter(isMeaningfulClass);
      if (classes.length === 0) return null;

      // Try tag + single meaningful class
      for (const cls of classes) {
        const selector = `${tag}.${CSS.escape(cls)}`;
        if (isUnique(selector, element)) return selector;
      }

      // Try tag + multiple classes
      if (classes.length > 1) {
        const selector = `${tag}${classes.map(c => `.${CSS.escape(c)}`).join('')}`;
        if (isUnique(selector, element)) return selector;
      }

      // Walk up to add parent context (max 3 levels)
      let parent = element.parentElement;
      for (let depth = 0; depth < 3 && parent; depth++) {
        const parentTag = parent.tagName.toLowerCase();

        // Parent has ID?
        if (parent.id && !isAutoGeneratedId(parent.id)) {
          const baseSelector = `${tag}${classes.map(c => `.${CSS.escape(c)}`).join('')}`;
          const selector = `#${CSS.escape(parent.id)} ${baseSelector}`;
          if (isUnique(selector, element)) return selector;
        }

        // Parent has meaningful classes?
        const parentClasses = Array.from(parent.classList).filter(isMeaningfulClass);
        if (parentClasses.length > 0) {
          const baseSelector = `${tag}${classes.map(c => `.${CSS.escape(c)}`).join('')}`;
          const parentSelector = `${parentTag}.${CSS.escape(parentClasses[0])}`;
          const selector = `${parentSelector} ${baseSelector}`;
          if (isUnique(selector, element)) return selector;
        }

        parent = parent.parentElement;
      }

      return null;
    },
  },

  // Strategy 4: Structural / nth-child fallback
  {
    name: 'structural',
    confidence: 'low',
    run(element) {
      const parts = [];
      let current = element;
      const maxDepth = 5;

      for (let depth = 0; depth < maxDepth && current && current !== document.documentElement; depth++) {
        const tag = current.tagName.toLowerCase();

        // Stop at a stable anchor
        if (current.id && !isAutoGeneratedId(current.id)) {
          parts.unshift(`#${CSS.escape(current.id)}`);
          break;
        }

        const dataTestId = current.getAttribute('data-testid');
        if (dataTestId) {
          parts.unshift(`[data-testid="${CSS.escape(dataTestId)}"]`);
          break;
        }

        const parent = current.parentElement;
        if (parent) {
          const sameTagSiblings = Array.from(parent.children).filter(c => c.tagName === current.tagName);
          if (sameTagSiblings.length > 1) {
            const index = sameTagSiblings.indexOf(current) + 1;
            parts.unshift(`${tag}:nth-of-type(${index})`);
          } else {
            parts.unshift(tag);
          }
        } else {
          parts.unshift(tag);
        }

        current = parent;
      }

      const selector = parts.join(' > ');
      try {
        if (isUnique(selector, element)) return selector;
      } catch {
        // invalid selector edge case
      }
      return null;
    },
  },
];

/**
 * Detect if element is inside a shadow DOM tree.
 * Returns an array of shadow boundaries from outermost to innermost.
 */
function getShadowBoundaries(element) {
  const boundaries = [];
  let root = element.getRootNode();
  while (root instanceof ShadowRoot) {
    boundaries.unshift(root.host);
    root = root.host.getRootNode();
  }
  return boundaries;
}

/**
 * Get the best selector for an element, with shadow DOM support.
 * @param {Element} element
 * @returns {{ selector: string, confidence: string, shadowDom: boolean }}
 */
function getBestSelector(element) {
  const boundaries = getShadowBoundaries(element);
  const inShadow = boundaries.length > 0;

  if (inShadow) {
    // Build composite selector across shadow boundaries
    const parts = [];

    // Selector for each shadow host
    for (const host of boundaries) {
      const hostResult = runStrategies(host);
      parts.push(hostResult.selector);
    }

    // Selector for the target element within its shadow root
    const innerResult = runStrategies(element);
    parts.push(innerResult.selector);

    return {
      selector: parts.join(' >> '),
      confidence: innerResult.confidence,
      shadowDom: true,
    };
  }

  const result = runStrategies(element);
  return { ...result, shadowDom: false };
}

/**
 * Run all strategies in order, return best result.
 */
function runStrategies(element) {
  for (const strategy of strategies) {
    const selector = strategy.run(element);
    if (selector) {
      return { selector, confidence: strategy.confidence };
    }
  }
  // Absolute fallback: tag name (may not be unique)
  return { selector: element.tagName.toLowerCase(), confidence: 'low' };
}

// Export for both browser and Node.js
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    getBestSelector, runStrategies, getShadowBoundaries, strategies,
    isUnique, isAutoGeneratedId, isMeaningfulClass,
  };
}
