// content/selector.js — Modular selector engine

/**
 * Check if a selector uniquely identifies the element in the document.
 */
function isUnique(selector, element) {
  try {
    const root = element.getRootNode();
    return root.querySelector(selector) === element;
  } catch {
    return false;
  }
}

/**
 * Heuristic: is this ID likely auto-generated?
 */
function isAutoGeneratedId(id) {
  if (!id) return true;
  // Contains sequences of 5+ digits, or matches framework patterns
  if (/\d{5,}/.test(id)) return true;
  if (/^(ember|react|ng-|css-|:r\d|radix-|headlessui-)/.test(id)) return true;
  if (/^[a-f0-9]{8,}$/.test(id)) return true; // hex hash
  return false;
}

/**
 * Heuristic: is this class name meaningful (not a utility/framework token)?
 */
function isMeaningfulClass(cls) {
  if (cls.length <= 1) return false;
  if (/^\d+$/.test(cls)) return false;
  // Filter framework utility classes
  if (/^(ng-|css-|_|svelte-|tw-|sc-|chakra-|MuiTypography|MuiButton|jsx-)/.test(cls)) return false;
  // CSS Modules: "Component-module__Name__hHXUL"
  if (/__[A-Za-z][\w]*__[A-Za-z0-9]{3,}$/.test(cls)) return false;
  // Styled-components with prefix: "Box-sc-62in7e-0"
  if (/-sc-[a-z0-9]+-/.test(cls)) return false;
  // Tailwind-like single-purpose classes (e.g., "p-4", "mt-2", "text-sm", "bg-red-500")
  if (/^[a-z]{1,3}-[\da-z]/.test(cls) && cls.length < 12) return false;
  return true;
}

// --- Selector strategies (ordered by priority) ---

const strategies = [
  // Strategy 1: ID
  {
    name: 'id',
    confidence: 'high',
    run(element) {
      const id = element.id;
      if (!id || isAutoGeneratedId(id)) return null;
      const selector = `#${CSS.escape(id)}`;
      return isUnique(selector, element) ? selector : null;
    },
  },

  // Strategy 2: Data / ARIA attributes (Playwright-style)
  {
    name: 'data-attr',
    confidence: 'high',
    run(element) {
      const attrs = ['data-testid', 'data-test', 'data-cy', 'data-qa', 'data-tag-name'];
      for (const attr of attrs) {
        const val = element.getAttribute(attr);
        if (val) {
          const selector = `[${attr}="${CSS.escape(val)}"]`;
          if (isUnique(selector, element)) return selector;
        }
      }
      // aria-label
      const ariaLabel = element.getAttribute('aria-label');
      if (ariaLabel) {
        const selector = `[aria-label="${CSS.escape(ariaLabel)}"]`;
        if (isUnique(selector, element)) return selector;
      }
      // name attribute
      const name = element.getAttribute('name');
      if (name) {
        const tag = element.tagName.toLowerCase();
        const selector = `${tag}[name="${CSS.escape(name)}"]`;
        if (isUnique(selector, element)) return selector;
      }
      // role + accessible name combo
      const role = element.getAttribute('role');
      if (role && ariaLabel) {
        const selector = `[role="${role}"][aria-label="${CSS.escape(ariaLabel)}"]`;
        if (isUnique(selector, element)) return selector;
      }
      return null;
    },
  },

  // Strategy 3: Class-based selector
  {
    name: 'class',
    confidence: 'medium',
    run(element) {
      const tag = element.tagName.toLowerCase();
      const classes = Array.from(element.classList).filter(isMeaningfulClass);
      if (classes.length === 0) return null;

      // Try tag + single meaningful class
      for (const cls of classes) {
        const selector = `${tag}.${CSS.escape(cls)}`;
        if (isUnique(selector, element)) return selector;
      }

      // Try tag + multiple classes
      if (classes.length > 1) {
        const selector = `${tag}${classes.map(c => `.${CSS.escape(c)}`).join('')}`;
        if (isUnique(selector, element)) return selector;
      }

      // Walk up to add parent context (max 3 levels)
      let parent = element.parentElement;
      for (let depth = 0; depth < 3 && parent; depth++) {
        const parentTag = parent.tagName.toLowerCase();

        // Parent has ID?
        if (parent.id && !isAutoGeneratedId(parent.id)) {
          const baseSelector = `${tag}${classes.map(c => `.${CSS.escape(c)}`).join('')}`;
          const selector = `#${CSS.escape(parent.id)} ${baseSelector}`;
          if (isUnique(selector, element)) return selector;
        }

        // Parent has meaningful classes?
        const parentClasses = Array.from(parent.classList).filter(isMeaningfulClass);
        if (parentClasses.length > 0) {
          const baseSelector = `${tag}${classes.map(c => `.${CSS.escape(c)}`).join('')}`;
          const parentSelector = `${parentTag}.${CSS.escape(parentClasses[0])}`;
          const selector = `${parentSelector} ${baseSelector}`;
          if (isUnique(selector, element)) return selector;
        }

        parent = parent.parentElement;
      }

      return null;
    },
  },

  // Strategy 3.5: Scoped descendant (classless element under a scoped ancestor)
  {
    name: 'scoped',
    confidence: 'medium',
    run(element) {
      const tag = element.tagName.toLowerCase();
      const LANDMARKS = ['article', 'main', 'nav', 'aside', 'header', 'footer', 'section', 'form'];
      const MAX_ANCESTORS = 10;

      // Helper: try selector candidates for a given prefix
      function tryCandidates(prefix, el) {
        const elTag = el.tagName.toLowerCase();
        // Simple: prefix + tag
        let sel = `${prefix} ${elTag}`;
        if (isUnique(sel, el)) return sel;

        // With immediate parent
        const parent = el.parentElement;
        if (parent) {
          const parentTag = parent.tagName.toLowerCase();
          sel = `${prefix} ${parentTag} > ${elTag}`;
          if (isUnique(sel, el)) return sel;

          // With nth-of-type on target within parent
          const sameTagSiblings = Array.from(parent.children).filter(c => c.tagName === el.tagName);
          if (sameTagSiblings.length > 1) {
            const idx = sameTagSiblings.indexOf(el) + 1;
            sel = `${prefix} ${parentTag} > ${elTag}:nth-of-type(${idx})`;
            if (isUnique(sel, el)) return sel;
          }
        }
        return null;
      }

      let ancestor = element.parentElement;
      for (let depth = 0; depth < MAX_ANCESTORS && ancestor; depth++) {
        // Try stable ID ancestors
        if (ancestor.id && !isAutoGeneratedId(ancestor.id)) {
          const prefix = `#${CSS.escape(ancestor.id)}`;
          const result = tryCandidates(prefix, element);
          if (result) return result;
        }

        // Try data-testid / data-tag-name ancestors
        for (const dataAttr of ['data-testid', 'data-tag-name']) {
          const val = ancestor.getAttribute(dataAttr);
          if (val) {
            const prefix = `[${dataAttr}="${CSS.escape(val)}"]`;
            const result = tryCandidates(prefix, element);
            if (result) return result;
          }
        }

        ancestor = ancestor.parentElement;
      }

      // Pass 2: meaningful class ancestors
      ancestor = element.parentElement;
      for (let depth = 0; depth < MAX_ANCESTORS && ancestor; depth++) {
        const ancestorTag = ancestor.tagName.toLowerCase();
        const ancestorClasses = Array.from(ancestor.classList).filter(isMeaningfulClass);
        for (const cls of ancestorClasses) {
          const prefix = `${ancestorTag}.${CSS.escape(cls)}`;
          const result = tryCandidates(prefix, element);
          if (result) return result;
        }
        ancestor = ancestor.parentElement;
      }

      // Pass 3: landmark ancestors
      ancestor = element.parentElement;
      for (let depth = 0; depth < MAX_ANCESTORS && ancestor; depth++) {
        const ancestorTag = ancestor.tagName.toLowerCase();
        if (LANDMARKS.includes(ancestorTag)) {
          const result = tryCandidates(ancestorTag, element);
          if (result) return result;
        }
        ancestor = ancestor.parentElement;
      }

      return null;
    },
  },

  // Strategy 4: Structural / nth-child fallback (anchor-first)
  {
    name: 'structural',
    confidence: 'low',
    run(element) {
      // Phase A: find nearest stable anchor (ID or data-testid) up to 15 levels
      let anchor = null;
      let anchorSelector = null;
      let scan = element.parentElement;
      for (let depth = 0; depth < 15 && scan && scan !== document.documentElement; depth++) {
        if (scan.id && !isAutoGeneratedId(scan.id)) {
          anchor = scan;
          anchorSelector = `#${CSS.escape(scan.id)}`;
          break;
        }
        const testId = scan.getAttribute('data-testid');
        if (testId) {
          anchor = scan;
          anchorSelector = `[data-testid="${CSS.escape(testId)}"]`;
          break;
        }
        scan = scan.parentElement;
      }

      // Phase B: build shortest path from anchor to target
      if (anchor) {
        const tag = element.tagName.toLowerCase();

        // Try descendant combinator only
        let sel = `${anchorSelector} ${tag}`;
        if (isUnique(sel, element)) return sel;

        // Build child-combinator path from target up to anchor, adding levels
        const pathParts = [];
        let current = element;
        const MAX_SEGMENTS = 5;
        for (let i = 0; i < MAX_SEGMENTS && current && current !== anchor; i++) {
          const t = current.tagName.toLowerCase();
          const parent = current.parentElement;
          if (parent) {
            const sameTagSiblings = Array.from(parent.children).filter(c => c.tagName === current.tagName);
            if (sameTagSiblings.length > 1) {
              const idx = sameTagSiblings.indexOf(current) + 1;
              pathParts.unshift(`${t}:nth-of-type(${idx})`);
            } else {
              pathParts.unshift(t);
            }
          } else {
            pathParts.unshift(t);
          }

          // After each level added, test if unique with descendant from anchor
          sel = `${anchorSelector} ${pathParts.join(' > ')}`;
          try {
            if (isUnique(sel, element)) return sel;
          } catch { /* skip */ }

          current = parent;
        }
      }

      // Phase C: fallback — chain logic with depth 8
      const parts = [];
      let current = element;
      const maxDepth = 8;

      for (let depth = 0; depth < maxDepth && current && current !== document.documentElement; depth++) {
        const tag = current.tagName.toLowerCase();

        if (current.id && !isAutoGeneratedId(current.id)) {
          parts.unshift(`#${CSS.escape(current.id)}`);
          break;
        }

        const dataTestId = current.getAttribute('data-testid');
        if (dataTestId) {
          parts.unshift(`[data-testid="${CSS.escape(dataTestId)}"]`);
          break;
        }

        const parent = current.parentElement;
        if (parent) {
          const sameTagSiblings = Array.from(parent.children).filter(c => c.tagName === current.tagName);
          if (sameTagSiblings.length > 1) {
            const index = sameTagSiblings.indexOf(current) + 1;
            parts.unshift(`${tag}:nth-of-type(${index})`);
          } else {
            parts.unshift(tag);
          }
        } else {
          parts.unshift(tag);
        }

        current = parent;
      }

      const selector = parts.join(' > ');
      try {
        if (isUnique(selector, element)) return selector;
      } catch {
        // invalid selector edge case
      }
      return null;
    },
  },
];

/**
 * Detect if element is inside a shadow DOM tree.
 * Returns an array of shadow boundaries from outermost to innermost.
 */
function getShadowBoundaries(element) {
  const boundaries = [];
  let root = element.getRootNode();
  while (root instanceof ShadowRoot) {
    boundaries.unshift(root.host);
    root = root.host.getRootNode();
  }
  return boundaries;
}

/**
 * Get the best selector for an element, with shadow DOM support.
 * @param {Element} element
 * @returns {{ selector: string, confidence: string, shadowDom: boolean }}
 */
function getBestSelector(element) {
  const boundaries = getShadowBoundaries(element);
  const inShadow = boundaries.length > 0;

  if (inShadow) {
    // Build composite selector across shadow boundaries
    const parts = [];

    // Selector for each shadow host
    for (const host of boundaries) {
      const hostResult = runStrategies(host);
      parts.push(hostResult.selector);
    }

    // Selector for the target element within its shadow root
    const innerResult = runStrategies(element);
    parts.push(innerResult.selector);

    return {
      selector: parts.join(' >> '),
      confidence: innerResult.confidence,
      shadowDom: true,
    };
  }

  const result = runStrategies(element);
  return { ...result, shadowDom: false };
}

/**
 * Run all strategies in order, return best result.
 */
function runStrategies(element) {
  for (const strategy of strategies) {
    const selector = strategy.run(element);
    if (selector) {
      return { selector, confidence: strategy.confidence };
    }
  }
  // Absolute fallback: tag name (may not be unique)
  return { selector: element.tagName.toLowerCase(), confidence: 'low' };
}

// Export for both browser and Node.js
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    getBestSelector, runStrategies, getShadowBoundaries, strategies,
    isUnique, isAutoGeneratedId, isMeaningfulClass,
  };
}
