// tests/selector.test.js — Unit tests for selector engine (plain JS, no framework)
// Run with: node extension/tests/selector.test.js

const assert = require('assert');

// Minimal DOM polyfill for testing
class MockElement {
  constructor(tag, attrs = {}, parent = null) {
    this.tagName = tag.toUpperCase();
    this.id = attrs.id || '';
    this.classList = new MockClassList(attrs.classes || []);
    this._attrs = { ...attrs };
    this.parentElement = parent;
    this.children = [];
    this.innerText = attrs.innerText || '';
    this.value = attrs.value || '';
    delete this._attrs.id;
    delete this._attrs.classes;
    delete this._attrs.innerText;
    delete this._attrs.value;
  }

  getAttribute(name) {
    if (name === 'id') return this.id || null;
    if (name === 'class') return this.classList._classes.join(' ') || null;
    return this._attrs[name] || null;
  }

  getRootNode() {
    // For non-shadow DOM tests, return document
    return mockDocument;
  }
}

class MockClassList {
  constructor(classes) {
    this._classes = classes;
    this.length = classes.length;
  }
  *[Symbol.iterator]() {
    for (const c of this._classes) yield c;
  }
  filter(fn) {
    return Array.from(this).filter(fn);
  }
}

// Mock CSS.escape
global.CSS = {
  escape: (str) => str.replace(/([^\w-])/g, '\\$1'),
};

// Mock document and ShadowRoot
let mockElements = new Map();
const mockDocument = {
  querySelector(sel) {
    return mockElements.get(sel) || null;
  },
  documentElement: new MockElement('html'),
};
global.document = mockDocument;
global.ShadowRoot = class ShadowRoot {};

// Register a mock element to be "found" by querySelector
function registerMock(selector, element) {
  mockElements.set(selector, element);
}

function clearMocks() {
  mockElements = new Map();
  mockDocument.querySelector = (sel) => mockElements.get(sel) || null;
}

// Load the module
const {
  isAutoGeneratedId,
  isMeaningfulClass,
  runStrategies,
  getBestSelector,
} = require('../content/selector.js');

// --- Test runner ---
let passed = 0;
let failed = 0;

function test(name, fn) {
  clearMocks();
  try {
    fn();
    passed++;
    console.log(`  \u2713 ${name}`);
  } catch (err) {
    failed++;
    console.log(`  \u2717 ${name}`);
    console.log(`    ${err.message}`);
  }
}

// --- Tests ---

console.log('\nisAutoGeneratedId:');

test('returns true for IDs with 5+ digits', () => {
  assert.strictEqual(isAutoGeneratedId('element12345'), true);
});

test('returns true for ember-style IDs', () => {
  assert.strictEqual(isAutoGeneratedId('ember123'), true);
});

test('returns true for React-style IDs', () => {
  assert.strictEqual(isAutoGeneratedId('react-12'), true);
});

test('returns true for hex hash IDs', () => {
  assert.strictEqual(isAutoGeneratedId('a1b2c3d4e5f6'), true);
});

test('returns true for :r0: style IDs', () => {
  assert.strictEqual(isAutoGeneratedId(':r0:'), true);
});

test('returns false for meaningful IDs', () => {
  assert.strictEqual(isAutoGeneratedId('login-form'), false);
});

test('returns false for simple IDs', () => {
  assert.strictEqual(isAutoGeneratedId('app'), false);
});

test('returns true for empty/null', () => {
  assert.strictEqual(isAutoGeneratedId(''), true);
  assert.strictEqual(isAutoGeneratedId(null), true);
});

console.log('\nisMeaningfulClass:');

test('returns false for single-char classes', () => {
  assert.strictEqual(isMeaningfulClass('a'), false);
});

test('returns false for numeric-only classes', () => {
  assert.strictEqual(isMeaningfulClass('123'), false);
});

test('returns false for framework utility classes', () => {
  assert.strictEqual(isMeaningfulClass('ng-scope'), false);
  assert.strictEqual(isMeaningfulClass('css-1a2b3c'), false);
  assert.strictEqual(isMeaningfulClass('svelte-abc'), false);
});

test('returns false for Tailwind-like utility classes', () => {
  assert.strictEqual(isMeaningfulClass('p-4'), false);
  assert.strictEqual(isMeaningfulClass('mt-2'), false);
  assert.strictEqual(isMeaningfulClass('bg-red-500'), false);
});

test('returns true for semantic class names', () => {
  assert.strictEqual(isMeaningfulClass('login-form'), true);
  assert.strictEqual(isMeaningfulClass('submit-btn'), true);
  assert.strictEqual(isMeaningfulClass('header'), true);
});

console.log('\nStrategy 1 - ID selector:');

test('uses ID when it exists and is unique', () => {
  const el = new MockElement('button', { id: 'submit' });
  registerMock('#submit', el);
  const result = runStrategies(el);
  assert.strictEqual(result.selector, '#submit');
  assert.strictEqual(result.confidence, 'high');
});

test('skips auto-generated IDs', () => {
  const el = new MockElement('button', { id: 'ember123' });
  // No data-attrs, no meaningful classes, so it falls through to structural
  const result = runStrategies(el);
  assert.notStrictEqual(result.selector, '#ember123');
});

console.log('\nStrategy 2 - Data attribute selector:');

test('uses data-testid when available and unique', () => {
  const el = new MockElement('button', { 'data-testid': 'submit-btn' });
  registerMock('[data-testid="submit-btn"]', el);
  const result = runStrategies(el);
  assert.strictEqual(result.selector, '[data-testid="submit-btn"]');
  assert.strictEqual(result.confidence, 'high');
});

test('uses data-tag-name when available and unique', () => {
  const el = new MockElement('div', { 'data-tag-name': 'user-card' });
  registerMock('[data-tag-name="user-card"]', el);
  const result = runStrategies(el);
  assert.strictEqual(result.selector, '[data-tag-name="user-card"]');
  assert.strictEqual(result.confidence, 'high');
});

test('uses aria-label when available and unique', () => {
  const el = new MockElement('button', { 'aria-label': 'Close dialog' });
  // CSS.escape escapes the space in the value
  registerMock('[aria-label="Close\\ dialog"]', el);
  const result = runStrategies(el);
  assert.strictEqual(result.selector, '[aria-label="Close\\ dialog"]');
  assert.strictEqual(result.confidence, 'high');
});

test('uses name attribute with tag when available and unique', () => {
  const el = new MockElement('input', { name: 'email' });
  registerMock('input[name="email"]', el);
  const result = runStrategies(el);
  assert.strictEqual(result.selector, 'input[name="email"]');
  assert.strictEqual(result.confidence, 'high');
});

console.log('\nStrategy 3 - Class-based selector:');

test('uses tag + meaningful class when unique', () => {
  const el = new MockElement('button', { classes: ['submit-btn'] });
  registerMock('button.submit-btn', el);
  const result = runStrategies(el);
  assert.strictEqual(result.selector, 'button.submit-btn');
  assert.strictEqual(result.confidence, 'medium');
});

test('adds parent context when needed', () => {
  const parent = new MockElement('form', { id: 'login-form' });
  const el = new MockElement('button', { classes: ['submit-btn'] }, parent);
  parent.children = [el];
  // Single class not unique
  registerMock('#login-form button.submit-btn', el);
  const result = runStrategies(el);
  assert.strictEqual(result.selector, '#login-form button.submit-btn');
  assert.strictEqual(result.confidence, 'medium');
});

console.log('\nisMeaningfulClass — CSS Modules & styled-components:');

test('returns false for CSS Module hash classes', () => {
  assert.strictEqual(isMeaningfulClass('Component-module__Name__hHXUL'), false);
  assert.strictEqual(isMeaningfulClass('styles-module__header__abc123'), false);
});

test('returns false for styled-components with prefix', () => {
  assert.strictEqual(isMeaningfulClass('Box-sc-62in7e-0'), false);
  assert.strictEqual(isMeaningfulClass('Wrapper-sc-abc123-1'), false);
});

test('still allows meaningful classes with underscores', () => {
  assert.strictEqual(isMeaningfulClass('my_component'), true);
  assert.strictEqual(isMeaningfulClass('page-header'), true);
});

console.log('\nStrategy 3.5 — Scoped descendant:');

test('classless element under ID ancestor → #id tag', () => {
  const grandparent = new MockElement('div', { id: 'repo-content' });
  const parent = new MockElement('div', {}, grandparent);
  const el = new MockElement('pre', {}, parent);
  grandparent.children = [parent];
  parent.children = [el];
  registerMock('#repo-content pre', el);
  const result = runStrategies(el);
  assert.strictEqual(result.selector, '#repo-content pre');
  assert.strictEqual(result.confidence, 'medium');
});

test('classless element under classed ancestor → ancestor.class tag', () => {
  const grandparent = new MockElement('div', { classes: ['js-snippet-clipboard'] });
  const parent = new MockElement('div', {}, grandparent);
  const el = new MockElement('pre', {}, parent);
  grandparent.children = [parent];
  parent.children = [el];
  registerMock('div.js-snippet-clipboard pre', el);
  const result = runStrategies(el);
  assert.strictEqual(result.selector, 'div.js-snippet-clipboard pre');
  assert.strictEqual(result.confidence, 'medium');
});

test('classless element needing parent disambiguation → #id parentTag > tag', () => {
  const grandparent = new MockElement('div', { id: 'content' });
  const parent = new MockElement('div', {}, grandparent);
  const el = new MockElement('pre', {}, parent);
  grandparent.children = [parent];
  parent.children = [el];
  // Simple #content pre is NOT unique — needs parent
  registerMock('#content div > pre', el);
  const result = runStrategies(el);
  assert.strictEqual(result.selector, '#content div > pre');
  assert.strictEqual(result.confidence, 'medium');
});

test('classless element with nth-of-type disambiguation', () => {
  const grandparent = new MockElement('div', { id: 'content' });
  const parent = new MockElement('div', {}, grandparent);
  const el1 = new MockElement('pre', {}, parent);
  const el2 = new MockElement('pre', {}, parent);
  grandparent.children = [parent];
  parent.children = [el1, el2];
  // Neither #content pre nor #content div > pre is unique
  registerMock('#content div > pre:nth-of-type(2)', el2);
  const result = runStrategies(el2);
  assert.strictEqual(result.selector, '#content div > pre:nth-of-type(2)');
  assert.strictEqual(result.confidence, 'medium');
});

test('scoped strategy uses data-testid ancestor', () => {
  const grandparent = new MockElement('div', { 'data-testid': 'code-block' });
  const parent = new MockElement('div', {}, grandparent);
  const el = new MockElement('pre', {}, parent);
  grandparent.children = [parent];
  parent.children = [el];
  registerMock('[data-testid="code-block"] pre', el);
  const result = runStrategies(el);
  assert.strictEqual(result.selector, '[data-testid="code-block"] pre');
  assert.strictEqual(result.confidence, 'medium');
});

test('scoped strategy uses landmark ancestor', () => {
  const article = new MockElement('article', {});
  const parent = new MockElement('div', {}, article);
  const el = new MockElement('pre', {}, parent);
  article.children = [parent];
  parent.children = [el];
  registerMock('article pre', el);
  const result = runStrategies(el);
  assert.strictEqual(result.selector, 'article pre');
  assert.strictEqual(result.confidence, 'medium');
});

console.log('\nStrategy 4 — Enhanced structural (anchor-first):');

test('finds distant ID anchor and uses descendant combinator', () => {
  // Build a deep chain: #root > div > div > div > div > div > span
  const root = new MockElement('div', { id: 'root' });
  let current = root;
  for (let i = 0; i < 5; i++) {
    const child = new MockElement('div', {}, current);
    current.children = [child];
    current = child;
  }
  const target = new MockElement('span', {}, current);
  current.children = [target];
  // Only the full descendant works — scoped strategy (3.5) picks it up at medium confidence
  registerMock('#root span', target);
  const result = runStrategies(target);
  assert.strictEqual(result.selector, '#root span');
  assert.strictEqual(result.confidence, 'medium');
});

test('structural builds path from anchor when descendant alone is not unique', () => {
  const root = new MockElement('div', { id: 'app' });
  const mid = new MockElement('section', {}, root);
  const parent = new MockElement('div', {}, mid);
  const el = new MockElement('span', {}, parent);
  root.children = [mid];
  mid.children = [parent];
  parent.children = [el];
  // #app span not unique, but #app span (path with nth) works
  registerMock('#app section > div > span', el);
  const result = runStrategies(el);
  assert.strictEqual(result.selector, '#app section > div > span');
  assert.strictEqual(result.confidence, 'low');
});

console.log('\nShadow DOM detection:');

test('getBestSelector returns shadowDom: false for normal elements', () => {
  const el = new MockElement('button', { id: 'submit' });
  registerMock('#submit', el);
  const result = getBestSelector(el);
  assert.strictEqual(result.shadowDom, false);
});

// --- Summary ---
console.log(`\n${passed + failed} tests: ${passed} passed, ${failed} failed\n`);
process.exit(failed > 0 ? 1 : 0);
